/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.ConexaoBD.Conexao;
import br.com.model.bean.Aluno;
import br.com.model.bean.Bairro;
import br.com.model.bean.Cep;
import br.com.model.bean.Cidade;
import br.com.model.bean.Curso;
import br.com.model.bean.Endereco;
import br.com.model.bean.Estado;
import br.com.model.bean.Horario;
import br.com.model.bean.Turma;
import br.com.model.bean.Turno;
import br.com.model.dao.AlunoDAO;
import br.com.model.dao.BairroDAO;
import br.com.model.dao.CepDAO;
import br.com.model.dao.CidadeDAO;
import br.com.model.dao.CursoDAO;
import br.com.model.dao.EnderecoDAO;
import br.com.model.dao.EstadoDAO;
import br.com.model.dao.HorarioDAO;
import br.com.model.dao.TurmaDAO;
import br.com.model.dao.TurnoDAO;
import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import br.com.tabelas.Tabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Matheus
 */
public final class Cad_Aluno extends javax.swing.JFrame {

    Aluno alu = new Aluno();
    AlunoDAO alunoDAO = new AlunoDAO();
    EnderecoDAO enderecoDAO = new EnderecoDAO();
    TurnoDAO turnodao = new TurnoDAO();
    TurmaDAO turmadao = new TurmaDAO();
    CursoDAO cursodao = new CursoDAO();
    EstadoDAO estadodao = new EstadoDAO();
    CidadeDAO cidadedao = new CidadeDAO();
    HorarioDAO horariodao = new HorarioDAO();
    BairroDAO bairrodao = new BairroDAO();
    CepDAO cepdao = new CepDAO();

    Conexao con = new Conexao();

    int CodEnd, CodTur, CodTurma, CodCur, CodSig, CodCid, flag = 0, CodAlu, CodHora, CodBairro, CodCep;

    public Cad_Aluno() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        con.conexao();

        preencherTabela("select * from view_aluno order by ALUNO");
        preencherTurno();
        preencherHorario();
        preencherTurma();
        preencherIDCurso();
        preencherSigla();
        preencherCidade();
        preencherBairro();
        preencherCep();
        preencherEndereco();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoNomeMãe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoNomePai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboEst_Civil = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        campoDTNascimento = new javax.swing.JFormattedTextField();
        campoRg = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        campocpf = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JFormattedTextField();
        comboSexo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtcep = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        btnBuscarCep = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtbairro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtrua = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtnumerocasa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtuf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtcidade = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtcomplemento = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        comboCursos = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        combodia = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        comboTurno = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        txtTurma = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtValorCurso = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tb_Aluno = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        campoPesquisar = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txthorario = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha de Cadastro");

        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Alunos");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/cliente.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nome Completo:");

        campoNome.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome Mãe:");

        campoNomeMãe.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nome Pai:");

        campoNomePai.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado Civil:");

        comboEst_Civil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado(a)", "Solteiro(a)", "Viuvo(a) " }));
        comboEst_Civil.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data Nascimento:");

        try {
            campoDTNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoDTNascimento.setEnabled(false);

        try {
            campoRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoRg.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RG:");

        try {
            campocpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campocpf.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CPF:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-MAIL:");

        campoEmail.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Telefone:");

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone.setEnabled(false);

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        comboSexo.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sexo:");

        try {
            txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcep.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CEP");

        btnBuscarCep.setText("Buscar");
        btnBuscarCep.setEnabled(false);
        btnBuscarCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCepActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Bairro:");

        txtbairro.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Rua:");

        txtrua.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nº:");

        txtnumerocasa.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("UF:");

        txtuf.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Cidade:");

        txtcidade.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Complemento:");

        txtcomplemento.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Curso:");

        comboCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PHP COMPLETO", "BANCO DE DADOS", "LOGICA DE PROGRAMAÇÃO" }));
        comboCursos.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Turno:");

        combodia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segunda - Feira", "Terça - Feira", "Quarta - Feira", "Quinta - Feira", "Sexta - Feira", "Sábado" }));
        combodia.setEnabled(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Dia:");

        comboTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno" }));
        comboTurno.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Turma:");

        txtTurma.setEnabled(false);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Valor:");

        txtValorCurso.setEnabled(false);

        botaoSalvar.setText("Salvar");
        botaoSalvar.setEnabled(false);
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        Tb_Aluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tb_Aluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_AlunoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tb_Aluno);

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/pesquisar.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Horario:");

        btnExcluir.setText("Exlcuir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(campoNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(campoNomeMãe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(campoNomePai, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(comboEst_Civil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(campoDTNascimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(campoRg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(campocpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(campoEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(campoTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(comboSexo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtcep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnBuscarCep, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtbairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtrua, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtnumerocasa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtuf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtcidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtcomplemento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(comboCursos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(combodia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(comboTurno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtTurma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtValorCurso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(botaoSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(campoPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnNovo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txthorario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(btnNovo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(botaoSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAlterar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(campoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisar)))
                                .addGap(52, 52, 52))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscarCep)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel15))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(combodia, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtbairro))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtrua, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnumerocasa, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtuf, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNomeMãe, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboEst_Civil, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDTNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRg, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campocpf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthorario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel25)))
                        .addGap(18, 18, 18)
                        .addComponent(txtValorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 112, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(campoNomeMãe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(campoNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(comboEst_Civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(campoDTNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(campoRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(campocpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCep)
                            .addComponent(jLabel15)
                            .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txtrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtnumerocasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txtuf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(comboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(combodia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(txtTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(txtValorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txthorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(campoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSalvar)
                    .addComponent(btnNovo)
                    .addComponent(btnCancelar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jDesktopPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void HabilitarCampos() {
        campoNome.setEnabled(true);
        campoNomeMãe.setEnabled(true);
        campoNomePai.setEnabled(true);
        comboEst_Civil.setEnabled(true);
        campoDTNascimento.setEnabled(true);
        campoRg.setEnabled(true);
        campocpf.setEnabled(true);
        campoEmail.setEnabled(true);
        campoTelefone.setEnabled(true);
        comboSexo.setEnabled(true);
        txtcep.setEnabled(true);
        txtbairro.setEnabled(true);
        txtrua.setEnabled(true);
        txtnumerocasa.setEnabled(true);
        txtuf.setEnabled(true);
        txtcidade.setEnabled(true);
        txtcomplemento.setEnabled(true);
        comboCursos.setEnabled(true);
        combodia.setEnabled(true);
        comboTurno.setEnabled(true);
        txtTurma.setEnabled(true);
        txtValorCurso.setEnabled(true);
    }

    public void DesabilitarCampos() {
        campoNome.setEnabled(false);
        campoNomeMãe.setEnabled(false);
        campoNomePai.setEnabled(false);
        comboEst_Civil.setEnabled(false);
        campoDTNascimento.setEnabled(false);
        campoRg.setEnabled(false);
        campocpf.setEnabled(false);
        campoEmail.setEnabled(false);
        campoTelefone.setEnabled(false);
        comboSexo.setEnabled(false);
        txtcep.setEnabled(false);
        txtbairro.setEnabled(false);
        txtrua.setEnabled(false);
        txtnumerocasa.setEnabled(false);
        txtuf.setEnabled(false);
        txtcidade.setEnabled(false);
        txtcomplemento.setEnabled(false);
        comboCursos.setEnabled(false);
        combodia.setEnabled(false);
        comboTurno.setEnabled(false);
        txtTurma.setEnabled(false);
        txtValorCurso.setEnabled(false);
    }

    public void LimparCampos() {
        campoNome.setText("");
        campoNomeMãe.setText("");
        campoNomePai.setText("");
        campoDTNascimento.setText("");
        campoRg.setText("");
        campocpf.setText("");
        campoEmail.setText("");
        campoTelefone.setText("");
        txtcep.setText("");
        txtbairro.setText("");
        txtrua.setText("");
        txtnumerocasa.setText("");
        txtuf.setText("");
        txtcidade.setText("");
        txtcomplemento.setText("");
        txtTurma.setText("");
        txtValorCurso.setText("");
    }

    public void HabilitarBotoes() {
        botaoSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnBuscarCep.setEnabled(true);
    }

    public void DesabilitarBotoes() {
        botaoSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnBuscarCep.setEnabled(false);
    }

    public void PesquisarPeloNome(String text) {
        alu.setPesquisa(campoPesquisar.getText());
        Aluno aluno = alunoDAO.buscarAluno(alu);
        campoNome.setText(aluno.getNome());
        campoNomeMãe.setText(aluno.getNome_mae());
        campoNomePai.setText(aluno.getNome_pai());
        comboEst_Civil.setSelectedItem(aluno.getEstado_civil());
        campoDTNascimento.setText(aluno.getDt_nascimento());
        campoRg.setText(aluno.getRg());
        campocpf.setText(aluno.getCpf());
        campoEmail.setText(aluno.getEmail());
        campoTelefone.setText(aluno.getTelefone());
        comboSexo.setSelectedItem(aluno.getSexo());
        txtcep.setText(aluno.getEndereco().getCep().getCep());
        txtbairro.setText(aluno.getEndereco().getCep().getBairro().getNome_bairro());
        txtnumerocasa.setText(aluno.getEndereco().getNumeroCasa());
        txtuf.setText(aluno.getEndereco().getCep().getBairro().getCidade().getEstado().getSigla());
        txtcidade.setText(aluno.getEndereco().getCep().getBairro().getCidade().getNome_cidade());
        txtcomplemento.setText(aluno.getEndereco().getComplemento());
        comboCursos.setSelectedItem(aluno.getCurso().getNomes_Curso());
        comboCursos.setSelectedItem(aluno.getCurso().getNomes_Curso());
        combodia.setSelectedItem(aluno.getCurso().getTurma().getHorario().getDia_curso());
        comboTurno.setSelectedItem(aluno.getCurso().getTurma().getTurno().getTurno_curso());
        txthorario.setText(aluno.getCurso().getTurma().getHorario().getHora_curso());
        txtTurma.setText(aluno.getCurso().getTurma().getTurma_curso());
       
    }

    public void preencherTurno() {
        con.conexao();
        con.executaSql("select*from tb_turno order by id_turno desc limit 1;");
        try {
            con.rs.first();

            do {
                CodTur = Integer.parseInt(con.rs.getString("id_turno"));

            } while (con.rs.next());

        } catch (SQLException ex) {
            //JOptionPane.showMessageDialog(null, "Erro na Consulta Turno/nErro!" + ex);
        }
    }

    public void preencherHorario() {
        con.conexao();
        con.executaSql("select*from tb_horario order by id_horario desc limit 1;");
        try {
            con.rs.first();

            do {
                CodHora = Integer.parseInt(con.rs.getString("id_horario"));

            } while (con.rs.next());

        } catch (SQLException ex) {
            // JOptionPane.showMessageDialog(null, "Erro na Consulta Turno/nErro!" + ex);
        }
    }

    public void preencherTurma() {
        con.conexao();
        con.executaSql("select * from tb_turma order by id_turma desc limit 1;");
        try {
            con.rs.first();

            do {
                CodTurma = Integer.parseInt(con.rs.getString("id_turma"));

            } while (con.rs.next());

        } catch (SQLException ex) {
            // JOptionPane.showMessageDialog(null, "Erro na Consulta Turma/nErro!" + ex);
        }
    }

    public void preencherIDCurso() {
        con.conexao();
        con.executaSql("select*from tb_curso order by id_curso desc limit 1;");
        try {
            con.rs.first();

            do {
                CodCur = Integer.parseInt(con.rs.getString("id_curso"));

            } while (con.rs.next());

        } catch (SQLException ex) {
            // JOptionPane.showMessageDialog(null, "Erro na Consulta Curso/nErro!" + ex);
        }
    }

    public void preencherSigla() {
        con.conexao();
        con.executaSql("select*from tb_estado order by id_estado desc limit 1;");
        try {
            con.rs.first();

            do {
                CodSig = Integer.parseInt(con.rs.getString("id_estado"));

            } while (con.rs.next());

        } catch (SQLException ex) {
            //  JOptionPane.showMessageDialog(null, "Erro na Consulta de Estado/nErro!" + ex);
        }
    }

    public void preencherCidade() {
        con.conexao();
        con.executaSql("select*from tb_cidade order by id_cidade desc limit 1;");
        try {
            con.rs.first();

            do {
                CodCid = Integer.parseInt(con.rs.getString("id_cidade"));

            } while (con.rs.next());

        } catch (SQLException ex) {
            //   JOptionPane.showMessageDialog(null, "Erro na Consulta de Cidade/nErro!" + ex);
        }
    }

    public void preencherBairro() {
        con.conexao();
        con.executaSql("select*from tb_bairro order by id_bairro desc limit 1;");
        try {
            con.rs.first();

            do {
                CodBairro = Integer.parseInt(con.rs.getString("id_bairro"));

            } while (con.rs.next());

        } catch (SQLException ex) {
            //  JOptionPane.showMessageDialog(null, "Erro na Consulta bairro/nErro!" + ex);
        }
    }

    public void preencherCep() {
        con.conexao();
        con.executaSql("select*from tb_cep order by id_cep desc limit 1;");
        try {
            con.rs.first();

            do {
                CodCep = Integer.parseInt(con.rs.getString("id_cep"));

            } while (con.rs.next());

        } catch (SQLException ex) {
            //  JOptionPane.showMessageDialog(null, "Erro na Consulta cep/nErro!" + ex);
        }
    }

    public void preencherEndereco() {
        con.conexao();
        con.executaSql("select*from tb_endereco order by id_endereco desc limit 1;");
        try {
            con.rs.first();

            do {
                CodEnd = Integer.parseInt(con.rs.getString("id_endereco"));
            } while (con.rs.next());

        } catch (SQLException ex) {
            //  JOptionPane.showMessageDialog(null, "Erro na Consulta/nErro!" + ex);
        }
    }

    private void btnBuscarCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCepActionPerformed
        ViaCEP viacep = new ViaCEP();
        try {
            viacep.buscar(txtcep.getText());
            txtbairro.setText(viacep.getBairro());
            txtrua.setText(viacep.getLogradouro());
            txtuf.setText(viacep.getUf());
            txtcidade.setText(viacep.getLocalidade());
            txtcomplemento.setText(viacep.getComplemento());
        } catch (ViaCEPException ex) {
            JOptionPane.showMessageDialog(null, "Cep não encontrado!");
        }
    }//GEN-LAST:event_btnBuscarCepActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if (flag == 1) {

            Turno turno = new Turno();
            turno.setTurno_curso((String) comboTurno.getSelectedItem());
            turnodao.save(turno);
            preencherTurno();

            turno.setId_turno(CodTur);

            Horario horario = new Horario();
            horario.setDia_curso((String) combodia.getSelectedItem());
            horario.setHora_curso(txthorario.getText());
            horariodao.save(horario);
            preencherHorario();

            horario.setId_horario(CodHora);

            Turma turma = new Turma();
            turma.setTurma_curso(txtTurma.getText());
            turma.setTurno(turno);
            turma.setHorario(horario);
            turmadao.save(turma);
            preencherTurma();
            turma.setId_turma(CodTurma);

            Curso curso = new Curso();

            curso.setNomes_Curso((String) comboCursos.getSelectedItem());
            curso.setValor_curso(Float.parseFloat(txtValorCurso.getText()));
            curso.setTurma(turma);
            cursodao.save(curso);
            preencherIDCurso();

            curso.setId_curso(CodCur);

            Estado estado = new Estado();
            estado.setSigla(txtuf.getText());
            estadodao.save(estado);
            preencherSigla();
            estado.setId_estado(CodSig);

            Cidade cidade = new Cidade();

            cidade.setNome_cidade(txtcidade.getText());
            cidade.setEstado(estado);
            cidadedao.save(cidade);
            preencherCidade();
            cidade.setId_cidade(CodCid);

            Bairro bairro = new Bairro();

            bairro.setNome_bairro(txtbairro.getText());
            bairro.setCidade(cidade);
            bairrodao.save(bairro);
            preencherBairro();
            bairro.setId_bairro(CodBairro);

            Cep cep = new Cep();

            cep.setBairro(bairro);
            cep.setCep(txtcep.getText());
            cepdao.save(cep);
            preencherCep();

            Endereco endereco = new Endereco();

            cep.setId_cep(CodCep);
            endereco.setCep(cep);
            endereco.setNomeRua(txtrua.getText());
            endereco.setNumeroCasa(txtnumerocasa.getText());
            endereco.setComplemento(txtcomplemento.getText());
            enderecoDAO.save(endereco);
            preencherEndereco();
            endereco.setId(CodEnd);

            preencherTabela("select * from view_aluno order by ALUNO");
            Aluno aluno = new Aluno();
            aluno.setNome(campoNome.getText());
            aluno.setNome_mae(campoNomeMãe.getText());
            aluno.setNome_pai(campoNomePai.getText());
            aluno.setEstado_civil((String) comboEst_Civil.getSelectedItem());
            aluno.setDt_nascimento(campoDTNascimento.getText());
            aluno.setRg(campoRg.getText());
            aluno.setCpf(campocpf.getText());
            aluno.setEmail(campoEmail.getText());
            aluno.setTelefone(campoTelefone.getText());
            aluno.setSexo((String) comboSexo.getSelectedItem());
            aluno.setEndereco(endereco);
            aluno.setCurso(curso);
            alunoDAO.save(aluno);
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja fazer mais alguma coisa?");
            if (resposta == JOptionPane.NO_OPTION) {
                dispose();
            }
            System.err.println("Salvo com sucesso!");
            preencherTabela("select * from view_aluno order by ALUNO");
            DesabilitarBotoes();
            DesabilitarCampos();
            LimparCampos();
            btnNovo.setEnabled(true);

        } else {

            /*Turno turno = new Turno();
        turno.setTurno_curso((String) comboTurno.getSelectedItem());
       // turnodao.save(turno);
        preencherTurno();

        turno.setId_turno(CodCur);

        Turma turma = new Turma();
        turma.setTurma_curso(txtTurma.getText());
        turma.setTurno(turno);
        //turmadao.save(turma);
        preencherTurma();

        Curso curso = new Curso();
        turma.setId_turma(CodTurma);
        curso.setNomes_Curso((String) comboCursos.getSelectedItem());
        curso.setValor_curso(Float.parseFloat(txtValorCurso.getText()));
        curso.setTurma(turma);
        //cursodao.save(curso);
        preencherIDCurso();

        curso.setId_curso(CodCur);

        Estado estado = new Estado();
        estado.setSigla(txtuf.getText());
       // estadodao.save(estado);
        preencherSigla();
        estado.setId_estado(CodSig);

        Cidade cidade = new Cidade();

        cidade.setNome_cidade(txtcidade.getText());
        cidade.setEstado(estado);
      //  cidadedao.save(cidade);
        preencherCidade();

        Endereco endereco = new Endereco();

        cidade.setId_cidade(CodCid);

        endereco.setCep(txtcep.getText());
        endereco.setBairro(txtbairro.getText());
        endereco.setNomeRua(txtrua.getText());
        endereco.setNumeroCasa(txtnumerocasa.getText());
        endereco.setCidade(cidade);
        endereco.setComplemento(txtcomplemento.getText());
       // enderecoDAO.save(endereco);
        preencherEndereco();
        endereco.setId(CodEnd);
             */
            preencherTabela("select * from view_aluno order by ALUNO");
            Aluno aluno = new Aluno();
            aluno.setId(CodAlu);
            aluno.setNome(campoNome.getText());
            aluno.setNome_mae(campoNomeMãe.getText());
            aluno.setNome_pai(campoNomePai.getText());
            aluno.setEstado_civil((String) comboEst_Civil.getSelectedItem());
            aluno.setDt_nascimento(campoDTNascimento.getText());
            aluno.setRg(campoRg.getText());
            aluno.setCpf(campocpf.getText());
            aluno.setEmail(campoEmail.getText());
            aluno.setTelefone(campoTelefone.getText());
            aluno.setSexo((String) comboSexo.getSelectedItem());
            alunoDAO.update(aluno);
            //System.err.println("Alterado com sucesso!");
            int resposta = 0;
            resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja fazer mais alguma coisa?");
            if (resposta == JOptionPane.NO_OPTION) {
                dispose();
            }
            preencherTabela("select * from view_aluno order by ALUNO");
            DesabilitarBotoes();
            DesabilitarCampos();
            LimparCampos();
            btnNovo.setEnabled(true);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        PesquisarPeloNome(campoPesquisar.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void Tb_AlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_AlunoMouseClicked
        btnAlterar.setEnabled(true);
        String nome = "" + Tb_Aluno.getValueAt(Tb_Aluno.getSelectedRow(), 1);
        con.conexao();
        con.executaSql("select * from view_aluno where ALUNO='" + nome + "'");
        try {
            con.rs.first();
            CodAlu = Integer.parseInt(con.rs.getString("CODIGO ALUNO"));
            campoNome.setText(con.rs.getString("ALUNO"));
            campoNomeMãe.setText(con.rs.getString("NOME MAE"));
            campoNomePai.setText(con.rs.getString("NOME PAI"));
            comboEst_Civil.setSelectedItem(con.rs.getString("ESTADO CIVIL"));
            campoDTNascimento.setText(con.rs.getString("DATA NASCIMENTO"));
            campoRg.setText(con.rs.getString("RG"));
            campocpf.setText(con.rs.getString("CPF"));
            campoEmail.setText(con.rs.getString("E-EMAIL"));
            campoTelefone.setText(con.rs.getString("CELULAR"));
            comboSexo.setSelectedItem(con.rs.getString("SEXO"));
            txtcep.setText(con.rs.getString("CEP"));
            txtbairro.setText(con.rs.getString("NOME BAIRRO"));
            txtrua.setText(con.rs.getString("LOGRADOURO"));
            txtnumerocasa.setText(con.rs.getString("NUMERO CASA"));
            txtuf.setText(con.rs.getString("SIGLA"));
            txtcidade.setText(con.rs.getString("CIDADE"));
            txtcomplemento.setText(con.rs.getString("COMPLEMENTO"));
            comboCursos.setSelectedItem(con.rs.getString("CURSO"));
            comboTurno.setSelectedItem(con.rs.getString("TURNO"));
            txtTurma.setText(con.rs.getString("TURMA"));
            txtValorCurso.setText(con.rs.getString("VALOR CURSO"));
            combodia.setSelectedItem(con.rs.getString("DIA"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no mouse clicked ao selecionar os dados" + ex);
        }
        con.desconecta();
    }//GEN-LAST:event_Tb_AlunoMouseClicked

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag = 1;
        HabilitarCampos();
        HabilitarBotoes();
        btnNovo.setEnabled(false);

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        LimparCampos();
        DesabilitarCampos();
        DesabilitarBotoes();
        btnNovo.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        flag = 2;
        HabilitarCampos();
        HabilitarBotoes();
        btnNovo.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void jDesktopPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseClicked

    }//GEN-LAST:event_jDesktopPane1MouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja Realmente Excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
            alu.setId(CodAlu);
            alunoDAO.delete(alu);
            LimparCampos();
            //DesabiliarCampos();
            //DesabilitarBotões();
            btnNovo.setEnabled(true);
            preencherTabela("select * from view_aluno order by ALUNO");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    public void preencherTabela(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nome", "Curso", "Cep", "Bairro", "Celular"};
        con.conexao();
        con.executaSql(Sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("CODIGO ALUNO"), con.rs.getString("ALUNO"), con.rs.getString("CURSO"),
                    con.rs.getString("CEP"), con.rs.getString("NOME BAIRRO"), con.rs.getString("CELULAR")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque Novamente");
        }
        Tabela tbaluno = new Tabela(dados, colunas);
        Tb_Aluno.setModel(tbaluno);
        Tb_Aluno.getColumnModel().getColumn(0).setPreferredWidth(30);
        Tb_Aluno.getColumnModel().getColumn(0).setResizable(false);
        Tb_Aluno.getColumnModel().getColumn(1).setPreferredWidth(160);
        Tb_Aluno.getColumnModel().getColumn(1).setResizable(false);
        Tb_Aluno.getColumnModel().getColumn(2).setPreferredWidth(220);
        Tb_Aluno.getColumnModel().getColumn(2).setResizable(false);
        Tb_Aluno.getColumnModel().getColumn(3).setPreferredWidth(83);
        Tb_Aluno.getColumnModel().getColumn(3).setResizable(false);
        Tb_Aluno.getColumnModel().getColumn(4).setPreferredWidth(160);
        Tb_Aluno.getColumnModel().getColumn(4).setResizable(false);
        Tb_Aluno.getColumnModel().getColumn(5).setPreferredWidth(130);
        Tb_Aluno.getColumnModel().getColumn(5).setResizable(false);
        Tb_Aluno.getTableHeader().setReorderingAllowed(false);
        Tb_Aluno.setAutoResizeMode(Tb_Aluno.AUTO_RESIZE_OFF);
        Tb_Aluno.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        con.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb_Aluno;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarCep;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JFormattedTextField campoDTNascimento;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNomeMãe;
    private javax.swing.JTextField campoNomePai;
    private javax.swing.JTextField campoPesquisar;
    private javax.swing.JFormattedTextField campoRg;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JFormattedTextField campocpf;
    private javax.swing.JComboBox<String> comboCursos;
    private javax.swing.JComboBox<String> comboEst_Civil;
    private javax.swing.JComboBox<String> comboSexo;
    private javax.swing.JComboBox<String> comboTurno;
    private javax.swing.JComboBox<String> combodia;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtTurma;
    private javax.swing.JTextField txtValorCurso;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JFormattedTextField txtcep;
    private javax.swing.JTextField txtcidade;
    private javax.swing.JTextField txtcomplemento;
    private javax.swing.JTextField txthorario;
    private javax.swing.JTextField txtnumerocasa;
    private javax.swing.JTextField txtrua;
    private javax.swing.JTextField txtuf;
    // End of variables declaration//GEN-END:variables
}
