/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.ConexaoBD.Conexao;
import br.com.tabelas.Tabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Matheus
 */
public class TL_PesquisarVenda extends javax.swing.JFrame {
    Conexao con = new Conexao();
    /**
     * Creates new form TL_PesquisarVenda
     */
    public TL_PesquisarVenda() {
        initComponents();
         con.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdata = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_VendasRealizadas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_DetalhesVenda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Digite uma Data:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vendas Realizdas");

        try {
            txtdata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tb_VendasRealizadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_VendasRealizadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_VendasRealizadasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_VendasRealizadas);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Detalhes da Venda");

        tb_DetalhesVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_DetalhesVenda);

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtdata, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscar))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(txtdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        setSize(new java.awt.Dimension(720, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        preencherTabelaAlunoPesq("select * from tb_venda inner join tb_aluno on tb_venda.id_aluno_venda = tb_aluno.id_aluno where data_venda ='" + txtdata.getText() + "'");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tb_VendasRealizadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_VendasRealizadasMouseClicked
        int cod = (int) tb_VendasRealizadas.getValueAt(tb_VendasRealizadas.getSelectedRow(), 0);
        preencherTabelaDetalhes("select * from tb_venda inner join tb_itens_vendas on tb_venda.id_venda = tb_itens_vendas.id_venda\n"
            + "inner join tb_curso on tb_itens_vendas.id_curso = tb_curso.id_curso where tb_venda.id_venda = "+ cod);
    }//GEN-LAST:event_tb_VendasRealizadasMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void preencherTabelaAlunoPesq(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Data Venda", "Valor da Venda", "Aluno"};
        con.conexao();
        con.executaSql(Sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_venda"), con.rs.getString("data_venda"), con.rs.getString("valor_total"),
                    con.rs.getString("nome")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque Novamente");
        }
        Tabela tbaluno = new Tabela(dados, colunas);
        tb_VendasRealizadas.setModel(tbaluno);
        tb_VendasRealizadas.getColumnModel().getColumn(0).setPreferredWidth(90);
        tb_VendasRealizadas.getColumnModel().getColumn(0).setResizable(false);
        tb_VendasRealizadas.getColumnModel().getColumn(1).setPreferredWidth(157);
        tb_VendasRealizadas.getColumnModel().getColumn(1).setResizable(false);
        tb_VendasRealizadas.getColumnModel().getColumn(2).setPreferredWidth(149);
        tb_VendasRealizadas.getColumnModel().getColumn(2).setResizable(false);
        tb_VendasRealizadas.getColumnModel().getColumn(3).setPreferredWidth(206);
        tb_VendasRealizadas.getColumnModel().getColumn(3).setResizable(false);
        tb_VendasRealizadas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tb_VendasRealizadas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        con.desconecta();
    }

    public void preencherTabelaDetalhes(String Sql) {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID","Curso", "Quantidade"};
        con.conexao();
        con.executaSql(Sql);
        try {
            con.rs.first();
            do {
                dados.add(new Object[]{con.rs.getInt("id_venda"),con.rs.getString("nome_curso"), con.rs.getString("quantidade")});
            } while (con.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Busque Novamente");
        }
        Tabela tbaluno = new Tabela(dados, colunas);
        tb_DetalhesVenda.setModel(tbaluno);
        tb_DetalhesVenda.getColumnModel().getColumn(0).setPreferredWidth(90);
        tb_DetalhesVenda.getColumnModel().getColumn(0).setResizable(false);
        tb_DetalhesVenda.getColumnModel().getColumn(1).setPreferredWidth(200);
        tb_DetalhesVenda.getColumnModel().getColumn(1).setResizable(false);
        tb_DetalhesVenda.getColumnModel().getColumn(2).setPreferredWidth(90);
        tb_DetalhesVenda.getColumnModel().getColumn(2).setResizable(false);
        tb_DetalhesVenda.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tb_DetalhesVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        con.desconecta();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TL_PesquisarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TL_PesquisarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TL_PesquisarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TL_PesquisarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TL_PesquisarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_DetalhesVenda;
    private javax.swing.JTable tb_VendasRealizadas;
    private javax.swing.JFormattedTextField txtdata;
    // End of variables declaration//GEN-END:variables
}
