/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.ConexaoBD.Conexao;
import br.com.model.bean.ParcelamentoVenda;
import br.com.model.dao.ParcelamentoVendaDAO;
import br.com.tabelas.Tabela;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Matheus
 */
public class TL_ParcelaVenda extends javax.swing.JFrame {

    //Variaveis Globais
    int qtdParcela, i = 1, cont = 1;// con usada para verificar quantas parcelas foram geradas
    float porc, valorVenda, valorParcela;

    Conexao con = new Conexao();

    ParcelamentoVenda parcela;
    ParcelamentoVendaDAO vendadao;

    /**
     * Creates new form TL_ParcelaVenda
     */
    public TL_ParcelaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        txtcodVenda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtvalorVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        txtJuros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtParcelas = new javax.swing.JTextField();
        btnParcelarVendas = new javax.swing.JButton();
        btnDuplicatas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_VendasParcelas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo Venda");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor da Venda");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Total");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Juros Parcelas");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Parcelas");

        btnParcelarVendas.setText("Parcelar");
        btnParcelarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcelarVendasActionPerformed(evt);
            }
        });

        btnDuplicatas.setText("Gerar Duplicatas");
        btnDuplicatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuplicatasActionPerformed(evt);
            }
        });

        tb_VendasParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb_VendasParcelas);

        jDesktopPane1.setLayer(txtcodVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtvalorVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtValorTotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtJuros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtParcelas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnParcelarVendas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnDuplicatas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(txtcodVenda)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(btnParcelarVendas)
                        .addGap(18, 18, 18)
                        .addComponent(btnDuplicatas))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJuros)
                            .addComponent(jLabel4)
                            .addComponent(txtvalorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtvalorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnParcelarVendas)
                    .addComponent(btnDuplicatas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(697, 491));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public TL_ParcelaVenda(int cod) {
        this.parcela = new ParcelamentoVenda();
        this.vendadao = new ParcelamentoVendaDAO();
        initComponents();
        con.conexao();

        con.executaSql("select * from tb_venda where id_venda =" + cod);
        try {
            con.rs.first();
            txtcodVenda.setText(String.valueOf(cod));
            txtvalorVenda.setText(String.valueOf(con.rs.getFloat("valor_total")));
            txtData.setText(String.valueOf(con.rs.getString("data_venda")));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar a Venda!\nERRO:" + ex);
        }

    }


    private void btnParcelarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcelarVendasActionPerformed
        qtdParcela = Integer.parseInt(txtParcelas.getText());
        porc = Float.parseFloat(txtJuros.getText());
        valorVenda = Float.parseFloat(txtvalorVenda.getText());
        valorParcela = valorVenda / qtdParcela;
        tb_VendasParcelas.removeAll();
        preencherTabela();
    }//GEN-LAST:event_btnParcelarVendasActionPerformed

    private void btnDuplicatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuplicatasActionPerformed
        int j = 1; //Controlar a inserção das parcelas no banco

        String datavenc;
        datavenc = txtData.getText();

        String dia, mes, ano; // Variaveis para armazenar a data
        dia = "" + datavenc.charAt(0) + datavenc.charAt(1) + "/";
        mes = "" + datavenc.charAt(3) + datavenc.charAt(4);
        ano = "/" + datavenc.charAt(6) + datavenc.charAt(7) + datavenc.charAt(8) + datavenc.charAt(9);

        int anoInt = Integer.parseInt("" + datavenc.charAt(6) + datavenc.charAt(7) + datavenc.charAt(8) + datavenc.charAt(9));
        int mesInt = Integer.parseInt(mes);

        while (j < cont) {
            if (mesInt < 10) {
                parcela.setCodVenda(Integer.parseInt(txtcodVenda.getText()));
                parcela.setValorParcela(valorParcela + (valorParcela * (porc / 100))); //Fórmula para calculo de porcentagem
                parcela.setValor_total(Float.parseFloat(txtValorTotal.getText()));
                parcela.setValor_venda(Float.parseFloat(txtvalorVenda.getText()));
                parcela.setNumeroParc(j);
                parcela.setDataVencimento(dia + "0" + mesInt + "/" + anoInt);
                vendadao.SalvarParcela(parcela);
            } else {
                parcela.setCodVenda(Integer.parseInt(txtcodVenda.getText()));
                parcela.setValorParcela(valorParcela + (valorParcela * (porc / 100))); //Fórmula para calculo de porcentagem
                parcela.setValor_total(Float.parseFloat(txtValorTotal.getText()));
                parcela.setValor_venda(Float.parseFloat(txtvalorVenda.getText()));
                parcela.setNumeroParc(j);
                parcela.setDataVencimento(dia + mesInt + "/" + anoInt);
                vendadao.SalvarParcela(parcela);
            }
            mesInt++;
            if (mesInt > 12) {
                anoInt++;
                mesInt = 1;
            }
            j++;
        }
        JOptionPane.showMessageDialog(rootPane, "Parcelas geradas!");
    }//GEN-LAST:event_btnDuplicatasActionPerformed

    public void preencherTabela() {
        ArrayList dados;
        dados = new ArrayList();

        String[] colunas;
        colunas = new String[]{"Código", "Mês", "Valor"};

        float valorAtuaParc, valorTotalVenda = 0;

        String data;
        data = txtData.getText();
        String dia, mes, ano; // Variaveis para armazenar a data
        dia = "" + data.charAt(0) + data.charAt(1) + "/";
        mes = "" + data.charAt(3) + data.charAt(4);
        ano = "/" + data.charAt(6) + data.charAt(7) + data.charAt(8) + data.charAt(9);

        valorAtuaParc = valorParcela + (valorParcela * (porc / 100)); //Fórmula para calculo de porcentagem
        int anoInt = Integer.parseInt("" + data.charAt(6) + data.charAt(7) + data.charAt(8) + data.charAt(9));
        int mesInt = Integer.parseInt(mes);

        while (i <= qtdParcela) {
            valorTotalVenda = valorTotalVenda + valorAtuaParc;
            if (mesInt < 10) {
                dados.add(new Object[]{i, dia + "0" + mesInt + "/" + anoInt, valorAtuaParc});
            } else {
                dados.add(new Object[]{i, dia + mesInt + "/" + anoInt, valorAtuaParc});
            }
            mesInt++;
            if (mesInt > 12) {
                anoInt++;
                mesInt = 1;
            }
            i++;
            cont++;
        }
        txtValorTotal.setText(String.valueOf(valorTotalVenda));
        Tabela tabelaVenda = new Tabela(dados, colunas);
        tb_VendasParcelas.setModel(tabelaVenda);
        tb_VendasParcelas.getColumnModel().getColumn(0).setPreferredWidth(50);
        tb_VendasParcelas.getColumnModel().getColumn(0).setResizable(false);
        tb_VendasParcelas.getColumnModel().getColumn(1).setPreferredWidth(157);
        tb_VendasParcelas.getColumnModel().getColumn(1).setResizable(false);
        tb_VendasParcelas.getColumnModel().getColumn(2).setPreferredWidth(157);
        tb_VendasParcelas.getColumnModel().getColumn(2).setResizable(false);
        tb_VendasParcelas.getTableHeader().setReorderingAllowed(false);
        tb_VendasParcelas.setAutoResizeMode(tb_VendasParcelas.AUTO_RESIZE_OFF);
        tb_VendasParcelas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        con.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TL_ParcelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TL_ParcelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TL_ParcelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TL_ParcelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TL_ParcelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDuplicatas;
    private javax.swing.JButton btnParcelarVendas;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_VendasParcelas;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtJuros;
    private javax.swing.JTextField txtParcelas;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtcodVenda;
    private javax.swing.JTextField txtvalorVenda;
    // End of variables declaration//GEN-END:variables
}
